name: Build Rust Executable with Cross

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with cross
        run: |
          cargo install cross --version 0.2.5
          cross build --release --target aarch64-unknown-linux-gnu
        env:
          DOCKER_API_VERSION: 1.41

      - name: Upload artifact
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: ironstream
          path: target/aarch64-unknown-linux-gnu/release/ironstream
