name: Validate Rust PR

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check Formatting with rustfmt
        run: cargo fmt --all -- --check

      - name: Run Clippy for Linting
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build (Debug Mode)
        run: cargo build
